server:
  port: 8088
  
---
spring:
  application:
    name: config-store-dev # 설정파일 YML 이름
  config:
    import: optional:configserver:http://localhost:9999
# test:
#   str: test-str

# actuator lib set
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans